name: Wurfelt
main: me.misoryan.wurfelt.Wurfelt
version: 1.1-MiMiPixel
author: Misoryan

permissions:
  Wurfelt.admin:
    default: op
    children:
      Wurfelt.broadcast: true
      Wurfelt.SS: true
      Wurfelt.Vanish: true
  Wurfelt.SS:
    description: Permission to use Freeze (Screen Share) Command.
    default: op

commands:
  wurfelt:
    description: Main Command.
  freeze:
    description: Freeze a player to use SS.
